#!/usr/bin/expect
spawn /usr/bin/loadingvnc
set Pass [lindex $argv 0]
expect "Password:"
send "$Pass\r"
expect "Verify:"
send "$Pass\r"
expect "Would you like to enter a view-only password (y/n)?"
send "\r"
interact
